// images.js
export const Images = {
  // Exits
  thumbpieceTrims: require('./Exits/thumbpieceTrims1.png'),
  wideCVR: require("./Exits/WideCVR.png"),
  wideStileRim: require("./Exits/Wide Rim Exit (8800).png"),
  wideSVR: require("./Exits/WideSVR.png"),
  wideNBSVR: require('./Exits/WideNBSVR.png'),
  wideMortise: require("./Exits/WideMortise.png"),
  narrowRimExit8500: require("./Exits/Narrow Rim Exit (8500).png"),
  narrowCVR9400: require("./Exits/narrowCVR 9400.png"),
  narrowCVR8400: require('./Exits/8400.png'),
  narrowMortise8300: require("./Exits/NarrowMortiseExit (8300).png"),
  narrowPE80Mortise: require("./Exits/narrowPE80Mortise.png"),
  narrowPECVR: require("./Exits/narrowPECVR.png"),
  narrowPE8500: require("./Exits/narrowPERim (PE8500).png"),
  PE80WideRimExit: require("./Exits/PE80 Wide Rim Exit.png"),
  LS8600CVRMortise: require("./Exits/LS8600 CVR Mortise.png"),
  crossWideRim: require("./Exits/crossWideRim.png"),
  crossWideSVR: require("./Exits/crossWideSVR.png"),
  crossWideMortise: require("./Exits/crossWideMortise.png"),
  widePERim: require('./Exits/PE80 Wide Rim Exit.png'),
  widePENBSVR: require("./Exits/widePENBSVR.png"),
  widePESVR: require("./Exits/widePESVR.png"),
  widePECVR: require("./Exits/widePECVR.png"),
  widePE80Mortise: require("./Exits/widePE80Mortise.png"),
  Exit2828: require('./Exits/20 Series Rim (2828).png'),
  Exit2727: require('./Exits/20 Series SVR (2727).png'),
  Exit3828: require('./Exits/30 Series Rim (3828).png'),
  strikes3828: require('./Exits/strikes3828.png'),
  strikes2828: require('./Exits/2828 Strikes.png'),

  // Multi Point Locks
  MP7000: require('./MultiPoints/7000.png'),
  MP6100: require('./MultiPoints/6100.png'),
  MP7300: require('./MultiPoints/7300.png'),

  // Mortise
  Mortise8200: require("./Mortise/MortiseLock.png"),
  Mortise9200: require("./Mortise/MortiseLock9200.png"),
  Mortise7800: require('./Mortise/7800.png'),
  MortiseM9200: require("./Mortise/MortiseM9200.png"),
  Mortise8200BHW: require("./Mortise/Mortise8200BHW.png"),
  Mortise8200BHL: require("./Mortise/BHL8200.png"),
  MortiseEscutcheon9200: require("./Mortise/MortiseEscutch9200.png"),
  MortiseElectrified8200: require("./Mortise/MortiseElectrified8200.png")
    ,
  MortiseIndicator8200: require("./Mortise/Mortise8200Indicator.png"),
  MortiseIndicatorSA190: require("./Mortise/MortiseIndicatorSA190.png"),
  MortiseIndicatorVN1: require("./Mortise/MortiseIndicatorVN1.png"),
  MortiseRoselessTrim: require("./Mortise/MortiseRoselessTrim.png"),
  ALP8200: require("./Mortise/ALP8200.png"),
  BHD9200: require("./Mortise/BHD9200.png"),
  Strike82007800: require("./Mortise/Strike 8200 7800.png"),
  Strikes9200: require("./Mortise/Strikes 9200.png"),
  ElectricHinge: require("./Mortise/ElectricHinge.png"),
  PT7800: require("./Mortise/PT7800.png"),

  // Bored
  Bored11: require("./Bored/Bored 11 Line.png"),
  Bored6: require("./Bored/Bored 6 Line.png"),
  Bored7: require("./Bored/Bored 7 Line.png"),
  Bored8x: require("./Bored/Bored 8x Line.png"),
  Bored10x: require("./Bored/Bored 10x Line.png"),
  Bored6500: require("./Bored/Bored 6500 Series.png"),
  BoredDLSeries: require("./Bored/Bored DL Series.png"),
  BoredLock: require("./Bored/Bored Lock.png"),
  BHW10x: require("./Bored/BHW10X.png"),

  // Auxiliary
  SSL1: require("./Aux Locks/Aux SSL1 Spring Latch.png"),
  Aux460: require("./Aux Locks/Aux 460 Deadbolt.png"),
  Aux480: require("./Aux Locks/Aux 480 Deadbolt.png"),
  Aux4870: require("./Aux Locks/Aux 4870 Deadbolt.png"),
  Aux8200: require("./Aux Locks/Aux 8200 Deadbolt.png"),
  AuxiliaryLocks: require("./Aux Locks/AuxiliaryLocks.png"),

  // Cylinders
  CylMortise: require('./Cylinders/CylinderMortise.png'),
  CylRim: require('./Cylinders/CylinderRim.png'),
  CylLFIC: require('./Cylinders/CylinderLFIC.png'),
  CylLFICCams: require('./Cylinders/CylinderLFICCams.png'),
  CylSFIC: require('./Cylinders/CylinderSFIC.png'),
  CylKESOF1: require('./Cylinders/CylinderKESOF1.png'),
  CylDegree: require('./Cylinders/CylinderDegree.png'),
  CylCams: require('./Cylinders/CylinderMortiseCams.png'),
  CylCam: require('./Cylinders/CylinderMortiseCam.png'),
  Cyl97Rosette: require('./Cylinders/Cylinder97Rosette.png'),
  CylRimParts: require('./Cylinders/CylinderRimParts.png'),
  CylMortiseParts: require('./Cylinders/CylinderMortiseParts.png'),
  CylSchlageKeyway: require('./Cylinders/CylinderCompetitorKeyway.png'),
  CylMortiseSizes: require('./Cylinders/CylinderMortiseSizes.png'),
  CylBored: require('./Cylinders/CylinderBored.png'),
  CylBoredLFIC: require('./Cylinders/CylinderLFICBored.png'),
  CylBoredSFIC: require('./Cylinders/CylinderSFICBored.png'),
  CylAllRegBored: require('./Cylinders/CylinderAllRegularBored.png'),
  CylCoreSFIC: require("./Cylinders/CylinderCoreSFIC.png"),
  CylHousingSFIC: require('./Cylinders/CylinderSFICWithHousing.png'),
  CylSFICKeyblanks: require('./Cylinders/CylinderSFICKeyblanks.png'),
  CylCoreLFIC: require('./Cylinders/CylinderCoreLFIC.png'),
  CylDegreeFixedCore: require('./Cylinders/CylinderDegreeFixedCore.png'),
  CylDegreeLFIC: require('./Cylinders/CylinderDegreeLFIC.png'),
  CylDegreeBored: require('./Cylinders/CylinderDegreeBored.png'),
  CylDegreeRim: require('./Cylinders/CylinderDegreeRim.png'),
  CylDegreeCams: require('./Cylinders/CylinderDegreeCams.png'),
  CylKESOMortise: require('./Cylinders/CylinderKESOMortise.png'),
  CylKESORim: require('./Cylinders/CylinderKESORim.png'),
  CylKESOBored: require('./Cylinders/CylinderKESOBored.png'),
  CylKESOCams: require('./Cylinders/CylinderKESOCam.png'),
  CylKeyBlanks: require('./Cylinders/CylinderKeyBlanks.png'),


  // Thermal Pins
  ThermalPin683: require('./thermal pins.png'),

  // KP Devices
  KP80Trim: require('./Exits/KP80 Keypad Escutcheon.png'),
  KP10X: require('./Bored/KP10X.png'),

  // IN Devices
  IN120: require('./Exits/IN120.png'),
  IN10X: require('./Bored/IN10X.png'),
  IN7900: require('./Mortise/IN7900.png'),
  IN120Rim: require('./Exits/IN120 Rim.png'),
  IN120Mortise: require('./Exits/IN120 Mortise.png'),

  // SN Devices
  SN200ET: require('./Exits/SNTrim 80.png'),
  SNPE8600: require('./Exits/SNPE8600.png'),
  SNPE8900: require('./Exits/SNPE8900.png'),
  SNPETRIM: require('./Exits/SNPETRIM.png')
};
